### ISSUE TITLE
docker-compose up on 6.x Exist cycle module dependencies

### ISSUE THREAD

**Issue by siegrainwong** [JaredTan95/skywalking-docker#23]
```bash
oap              | 2019-05-22 20:26:59,154 - org.apache.skywalking.oap.server.starter.OAPServerStartUp -2520 [main] ERROR [] - Exist cycle module dependencies in
oap              | core[provider=org.apache.skywalking.oap.server.core.CoreModuleProvider]
oap              | service-mesh[provider=org.apache.skywalking.aop.server.receiver.mesh.MeshReceiverProvider]
oap              | alarm[provider=org.apache.skywalking.oap.server.core.alarm.provider.AlarmModuleProvider]
oap              | receiver-trace[provider=org.apache.skywalking.oap.server.receiver.trace.provider.TraceModuleProvider]
oap              | storage[provider=org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider]
oap              | istio-telemetry[provider=org.apache.skywalking.oap.server.receiver.istio.telemetry.provider.IstioTelemetryReceiverProvider]
oap              | receiver-jvm[provider=org.apache.skywalking.oap.server.receiver.jvm.provider.JVMModuleProvider]
oap              | receiver-register[provider=org.apache.skywalking.oap.server.receiver.register.provider.RegisterModuleProvider]
oap              | org.apache.skywalking.oap.server.library.module.CycleDependencyException: Exist cycle module dependencies in
oap              | core[provider=org.apache.skywalking.oap.server.core.CoreModuleProvider]
oap              | service-mesh[provider=org.apache.skywalking.aop.server.receiver.mesh.MeshReceiverProvider]
oap              | alarm[provider=org.apache.skywalking.oap.server.core.alarm.provider.AlarmModuleProvider]
oap              | receiver-trace[provider=org.apache.skywalking.oap.server.receiver.trace.provider.TraceModuleProvider]
oap              | storage[provider=org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider]
oap              | istio-telemetry[provider=org.apache.skywalking.oap.server.receiver.istio.telemetry.provider.IstioTelemetryReceiverProvider]
oap              | receiver-jvm[provider=org.apache.skywalking.oap.server.receiver.jvm.provider.JVMModuleProvider]
oap              | receiver-register[provider=org.apache.skywalking.oap.server.receiver.register.provider.RegisterModuleProvider]
oap              |      at org.apache.skywalking.oap.server.library.module.BootstrapFlow.makeSequence(BootstrapFlow.java:108) ~[library-module-6.1.0.jar:6.1.0]
oap              |      at org.apache.skywalking.oap.server.library.module.BootstrapFlow.<init>(BootstrapFlow.java:38) ~[library-module-6.1.0.jar:6.1.0]
oap              |      at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:63) ~[library-module-6.1.0.jar:6.1.0]
oap              |      at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:43) [server-starter-6.1.0.jar:6.1.0]
oap exited with code 1
```
Have any idea how to fix this? thx~

**Comment by JaredTan95** [comment]
fixed : https://github.com/JaredTan95/skywalking-docker/commit/dbd2cc24606e99fdd11c4700c2f6f8d1a4f6643c
