### ISSUE TITLE
6.X docker-compose 启动，报错

### ISSUE THREAD

**Issue by ldw4033** [JaredTan95/skywalking-docker#26]
08:58:46.619 [main] ERROR org.apache.skywalking.oap.server.starter.OAPServerStartUp - file not found: application.yml
org.apache.skywalking.oap.server.starter.config.ConfigFileNotFoundException: file not found: application.yml
        at org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader.loadConfig(ApplicationConfigLoader.java:84) ~[server-starter-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader.load(ApplicationConfigLoader.java:49) ~[server-starter-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:42) [server-starter-6.1.0.jar:6.1.0]
Caused by: java.io.FileNotFoundException: file not found: application.yml
        at org.apache.skywalking.oap.server.library.util.ResourceUtils.read(ResourceUtils.java:32) ~[library-util-6.1.0.jar:6.1.0]
        at org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader.loadConfig(ApplicationConfigLoader.java:57) ~[server-starter-6.1.0.jar:6.1.0]
        ... 2 more

**Comment by JaredTan95** [comment]
你用的这个仓库里面的docker-compose.yml文件？

**Comment by JaredTan95** [comment]
我这里启动OK呢，你检查一下你是不是改动这里了：
```
    volumes:
      - ../config:/apache-skywalking-apm-bin/config:ro
```

**Comment by ldw4033** [comment]
抱歉。我没有仔细看docker-compose.yml 文件，导致我没有copy config 文件夹下的配置文件，导致文件找不到。谢谢啦！

**Comment by ldw4033** [comment]
tips:启动 docker-compose up -d 之前，先将6.x/config 下的配置文件copy到服务器上指定位置。
