### ISSUE TITLE
SkyApm.Transport.Grpc.ConnectionManager : Connect server timeout.

### ISSUE THREAD

**Issue by kisshexuxia** [JaredTan95/skywalking-docker#29]
环境是Centos7 通过docker-compose安装后、可以正常打开8080控制台界面。Centos7的防火墙也是关闭了的。
但是新增DEMO API WebApplication1一直提示Connect server timeout.

`[root@localhost ~]# docker ps
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS                       PORTS                                            NAMES
081e0b046b07        wutang/skywalking-ui:6.1.0                 "sh docker-entrypo..."   11 hours ago        Up 11 hours                  11800/tcp, 0.0.0.0:8080->8080/tcp, 12800/tcp     ui
628d03b52c45        wutang/skywalking-oap:6.1.0                "sh docker-entrypo..."   11 hours ago        Restarting (1) 4 hours ago                                                    oap
d302ed2d5f82        wutang/elasticsearch-shanghai-zone:6.3.2   "/usr/local/bin/do..."   11 hours ago        Up 11 hours                  0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp   elasticsearch`
`2019-09-18 19:59:42.496 +08:00 [WebApplication1] [Error] SkyApm.Transport.Grpc.ConnectionManager : Connect server timeout.
System.Threading.Tasks.TaskCanceledException: Reached deadline.
   at Grpc.Core.Channel.WaitForStateChangedAsync(ChannelState lastObservedState, Nullable`1 deadline) in T:\src\github\grpc\src\csharp\Grpc.Core\Channel.cs:line 139
   at Grpc.Core.Channel.ConnectAsync(Nullable`1 deadline) in T:\src\github\grpc\src\csharp\Grpc.Core\Channel.cs:line 220
   at SkyApm.Transport.Grpc.ConnectionManager.ConnectAsync()
2019-09-18 19:59:47.246 +08:00 [WebApplication1] [Information] SkyApm.Transport.Grpc.ConnectionManager : Shutdown connection[192.168.0.17:11800].
`

`{
  "SkyWalking": {
    "ServiceName": "WebApplication1",
    "Namespace": "",
    "HeaderVersions": [
      "sw6"
    ],
    "Sampling": {
      "SamplePer3Secs": -1,
      "Percentage": -1.0
    },
    "Logging": {
      "Level": "Information",
      "FilePath": "logs\\skyapm-{Date}.log"
    },
    "Transport": {
      "Interval": 3000,
      "ProtocolVersion": "v6",
      "QueueSize": 30000,
      "BatchSize": 3000,
      "gRPC": {
        "Servers": "192.168.0.17:11800",
        "Timeout": 10000,
        "ConnectTimeout": 10000,
        "ReportTimeout": 600000
      }
    }
  }
}`

**Comment by ming200825** [comment]
2019-09-25 11:37:01.850 +08:00 [sample_app] [Information] SkyApm.InstrumentStartup : Initializing ...
2019-09-25 11:37:01.928 +08:00 [sample_app] [Information] SkyApm.Service.RegisterService : Loaded instrument service [SkyApm.Service.RegisterService].
2019-09-25 11:37:01.934 +08:00 [sample_app] [Information] SkyApm.Service.PingService : Loaded instrument service [SkyApm.Service.PingService].
2019-09-25 11:37:01.934 +08:00 [sample_app] [Information] SkyApm.Service.ServiceDiscoveryV5Service : Loaded instrument service [SkyApm.Service.ServiceDiscoveryV5Service].
2019-09-25 11:37:01.934 +08:00 [sample_app] [Information] SkyApm.Service.SegmentReportService : Loaded instrument service [SkyApm.Service.SegmentReportService].
2019-09-25 11:37:01.935 +08:00 [sample_app] [Information] SkyApm.Service.CLRStatsService : Loaded instrument service [SkyApm.Service.CLRStatsService].
2019-09-25 11:37:01.935 +08:00 [sample_app] [Information] SkyApm.Sampling.SimpleCountSamplingInterceptor : Loaded instrument service [SkyApm.Sampling.SimpleCountSamplingInterceptor].
2019-09-25 11:37:01.935 +08:00 [sample_app] [Information] SkyApm.Transport.Grpc.V6.ConnectService : Loaded instrument service [SkyApm.Transport.Grpc.V6.ConnectService].
2019-09-25 11:37:02.087 +08:00 [sample_app] [Information] SkyApm.Diagnostics.TracingDiagnosticProcessorObserver : Loaded diagnostic listener [Microsoft.AspNetCore].
2019-09-25 11:37:02.087 +08:00 [sample_app] [Information] SkyApm.InstrumentStartup : Started SkyAPM .NET Core Agent.
2019-09-25 11:37:17.530 +08:00 [sample_app] [Error] SkyApm.Transport.Grpc.ConnectionManager : Connect server timeout.
System.Threading.Tasks.TaskCanceledException: Reached deadline.
   at Grpc.Core.Channel.WaitForStateChangedAsync(ChannelState lastObservedState, Nullable`1 deadline)
   at Grpc.Core.Channel.ConnectAsync(Nullable`1 deadline)
   at SkyApm.Transport.Grpc.ConnectionManager.ConnectAsync()
2019-09-25 11:37:17.698 +08:00 [sample_app] [Information] SkyApm.Transport.Grpc.ConnectionManager : Shutdown connection[172.19.0.2:11800].
2019-09-25 11:37:27.860 +08:00 [sample_app] [Error] SkyApm.Transport.Grpc.ConnectionManager : Connect server timeout.
System.Threading.Tasks.TaskCanceledException: Reached deadline.
   at Grpc.Core.Channel.WaitForStateChangedAsync(ChannelState lastObservedState, Nullable`1 deadline)
   at Grpc.Core.Channel.ConnectAsync(Nullable`1 deadline)
   at SkyApm.Transport.Grpc.ConnectionManager.ConnectAsync()
2019-09-25 11:37:33.857 +08:00 [sample_app] [Information] SkyApm.Transport.Grpc.ConnectionManager : Shutdown connection[172.19.0.2:11800].
2019-09-25 11:37:44.017 +08:00 [sample_app] [Error] SkyApm.Transport.Grpc.ConnectionManager : Connect server timeout.
System.Threading.Tasks.TaskCanceledException: Reached deadline.
   at Grpc.Core.Channel.WaitForStateChangedAsync(ChannelState lastObservedState, Nullable`1 deadline)
   at Grpc.Core.Channel.ConnectAsync(Nullable`1 deadline)
   at SkyApm.Transport.Grpc.ConnectionManager.ConnectAsync()
2019-09-25 11:37:47.109 +08:00 [sample_app] [Information] SkyApm.Transport.Grpc.ConnectionManager : Shutdown connection[172.19.0.2:11800].
2019-09-25 11:37:57.398 +08:00 [sample_app] [Error] SkyApm.Transport.Grpc.ConnectionManager : Connect server timeout.
System.Threading.Tasks.TaskCanceledException: Reached deadline.
   at Grpc.Core.Channel.WaitForStateChangedAsync(ChannelState lastObservedState, Nullable`1 deadline)
   at Grpc.Core.Channel.ConnectAsync(Nullable`1 deadline)
   at SkyApm.Transport.Grpc.ConnectionManager.ConnectAsync()
2019-09-25 11:38:06.254 +08:00 [sample_app] [Information] SkyApm.Transport.Grpc.ConnectionManager : Shutdown connection[172.19.0.2:11800].

**Comment by kisshexuxia** [comment]
原因我已经知道、我用skywalking-docker部署后、服务器端口11800、12800开始是在oap 下面的、过来一会到 11800/tcp, 0.0.0.0:8080->8080/tcp, 12800/tcp ui 下面去了。所以端口一直是没通的。
可以用netstat -lntp查看下端口。
