### ISSUE TITLE
skywalking 500错误

### ISSUE THREAD

**Issue by naah69** [JaredTan95/skywalking-docker#9]
skywalking 500错误
于是我把日志映射了出来，通过看日志发现无法连接127.0.0.1:10800
通过telnet 对ip和端口进行测试
发现10800 11800 12800都没有启动，只有8080启动了

**Comment by JaredTan95** [comment]
你可以把日志挂载出来，看看日志，有可能是es没有配置正确。

**Comment by naah69** [comment]
日志映射的是 /apache-skywalking-apm-incubating/logs
只是显示无法连接端口

我用k8s搭建的，想知道以哪个docker run为准啊

**Comment by naah69** [comment]
https://github.com/JaredTan95/skywalking-docker/tree/master/5.x/quick-start

https://hub.docker.com/r/wutang/skywalking-docker/

这两个哪个为准

**Comment by JaredTan95** [comment]
> https://github.com/JaredTan95/skywalking-docker/tree/master/5.x/quick-start
> 
> https://hub.docker.com/r/wutang/skywalking-docker/
> 
> 这两个哪个为准

这两个是同一个镜像哦，第二个是我通过dockerhub自动构建出来的，源码在第一个链接的github。仅此而已。

如果你用k8s搭建，要看你是搭建集群还是单机模式的。

**Comment by li-xunhuan** [comment]
我也遇到这个问题了~~

**Comment by jueding920** [comment]
我也遇到了 按文档的启动死活都是500

**Comment by linfangrong** [comment]
500错误，有些参数是错的。。。 已提merge

https://github.com/JaredTan95/skywalking-docker/pull/14

找了半天的错误。。。

**Comment by JaredTan95** [comment]
@linfangrong  非常感谢～

**Comment by naah69** [comment]
![image](https://user-images.githubusercontent.com/25682169/51017113-c202ce00-15ad-11e9-9715-c9208f3056a3.png)
![image](https://user-images.githubusercontent.com/25682169/51017125-cb8c3600-15ad-11e9-8433-50e2e0485ca7.png)

**Comment by naah69** [comment]
![image](https://user-images.githubusercontent.com/25682169/51017149-e8c10480-15ad-11e9-99bd-dd16be29b708.png)

**Comment by linfangrong** [comment]
@naah69  你把配置改一下...  MONTH_METRIC_DATA_TTL

**Comment by naah69** [comment]
![image](https://user-images.githubusercontent.com/25682169/51018151-823de580-15b1-11e9-9bf5-0ef0cdb8bd0f.png)
容器内部还有端口占用啊

**Comment by naah69** [comment]
@linfangrong 大佬，改哪个配置  环境变量还是什么 MONTH_METRIC_DATA_TTL
我看不是已经重新打包么了

**Comment by linfangrong** [comment]
@naah69 我看作者2天前编译失败了，你拉下最新代码自己编一下。

docker run -p 8080:8080 -p 10800:10800 -p 11800:11800 -p 12800:12800 -m 2048m --memory-swap 2400m -e DAE_SEGMENT="^172\.17\.\d{1,3}.\d{1,3}$" -e JAVA_OPTS="-Xms1024m -Xmx2048m" -e ES_CLUSTER_NAME=elasticsearch -e ES_ADDRESSES=xxx.xxx.xxx.xxx:9300 -e UI_ADMIN_PASSWORD=admin -e MONTH_METRIC_DATA_TTL=18 -e UI_JETTY_BIND_PORT=12800 -e UI_JETTY_BIND_HOST=0.0.0.0 -e UI_SERVER_PORT=8081 -e UI_RIBBON_LIST_SERVERS=127.0.0.1:10800  -d wutang/skywalking-docker:5.x

**Comment by naah69** [comment]
自己编译了一下  但是还是启动失败，日志里有端口占用
```
2019-01-11 15:49:59,983 - org.apache.skywalking.apm.collector.jetty.manager.JettyManagerProvider -14958 [main] ERROR [] - Address already in use
org.apache.skywalking.apm.collector.server.jetty.JettyServerException: Address already in use
	at org.apache.skywalking.apm.collector.server.jetty.JettyServer.start(JettyServer.java:96) ~[server-component-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.jetty.manager.JettyManagerProvider.lambda$notifyAfterCompleted$0(JettyManagerProvider.java:68) ~[collector-jetty-manager-provider-5.0.0-GA.jar:5.0.0-GA]
	at java.util.HashMap$Values.forEach(HashMap.java:980) [?:1.8.0_111]
	at org.apache.skywalking.apm.collector.jetty.manager.JettyManagerProvider.notifyAfterCompleted(JettyManagerProvider.java:66) [collector-jetty-manager-provider-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.core.module.BootstrapFlow.notifyAfterCompleted(BootstrapFlow.java:67) [apm-collector-core-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:69) [apm-collector-core-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:45) [apm-collector-boot-5.0.0-GA.jar:5.0.0-GA]
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_111]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_111]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_111]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_111]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_111]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:298) ~[jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236) ~[jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.server.Server.doStart(Server.java:431) ~[jetty-server-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.2.v20170220.jar:9.4.2.v20170220]
	at org.apache.skywalking.apm.collector.server.jetty.JettyServer.start(JettyServer.java:94) ~[server-component-5.0.0-GA.jar:5.0.0-GA]
	... 6 more
```

**Comment by andycode112** [comment]
我也碰到了同样的问题，请问如何解决？

**Comment by swjmy** [comment]
同样的问题+1
